# See: https://docs.github.com/en/actions/writing-workflows
---
name: Build ASIMOV rust package

on:
  workflow_call:
    inputs:
      enabled:
        required: false
        type: boolean
        default: true
      os:
        required: true
        type: string
      artifact:
        required: true
        type: string
      target:
        required: true
        type: string
      custom_step:
        required: false
        type: string
      custom_brew_step:
        required: false
        type: string
      build_homebrew_bottle:
        required: false
        type: boolean
        default: false
      bump_homebrew_formula:
        required: false
        type: boolean
        default: true
      use_zigbuild:
        required: false
        type: boolean
        default: false
      glibc_version:
        required: false
        type: string
        default: ""
      extension:
        required: false
        type: string
        default: ""
      rust_toolchain:
        required: false
        type: string
        default: "stable"
      env:
        required: false
        type: string
    secrets:
      ASIMOV_APP_ID:
        required: true
      ASIMOV_APP_PRIVATE_KEY:
        required: true
      ENV:
        required: false

jobs:
  build-rust-package:
    name: Build ${{ inputs.artifact }} binary
    if: ${{ inputs.enabled }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Set environment variables
        uses: asimov-platform/actions/set-env-vars@master
        with:
          env: ${{ inputs.env }}
          secret_env: ${{ secrets.ENV }}
      - name: Install dependencies
        if: ${{ inputs.custom_step != '' }}
        run: ${{ inputs.custom_step }}
      - name: Build
        uses: asimov-platform/build-rust-action@v6
        with:
          target: ${{ inputs.target }}
          gh-artifact-prefix: "file-"
          artifact-suffix: ${{ inputs.artifact }}
          binary-extension: ${{ inputs.extension }}
          use-zigbuild: ${{ inputs.use_zigbuild || 'false' }}
          glibc-version: ${{ inputs.glibc_version }}
          rust-toolchain: ${{ inputs.rust_toolchain }}
  build-homebrew-bottle:
    name: Build ${{ inputs.artifact }} bottle
    if: ${{ inputs.enabled && inputs.build_homebrew_bottle }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Set environment variables
        uses: asimov-platform/actions/set-env-vars@master
        with:
          env: ${{ inputs.env }}
          secret_env: ${{ secrets.ENV }}
      - name: Install dependencies
        if: ${{ inputs.custom_brew_step != '' }}
        run: ${{ inputs.custom_brew_step }}
      - name: Build
        uses: asimov-platform/actions/build-homebrew-bottle@master
        with:
          bump_formula: ${{ inputs.bump_homebrew_formula }}
          app_id: ${{ secrets.ASIMOV_APP_ID }}
          app_private_key: ${{ secrets.ASIMOV_APP_PRIVATE_KEY }}
