# See: https://docs.github.com/en/actions/writing-workflows
---
name: Release ASIMOV Rust package

on:
  workflow_call:
    inputs:
      changelog_path:
        required: false
        type: string
        default: "CHANGES.md"
    outputs:
      assets:
        value: ${{ jobs.release.outputs.assets }}
      url:
        value: ${{ jobs.release.outputs.url }}
    secrets:
      ASIMOV_APP_ID:
        required: true
      ASIMOV_APP_PRIVATE_KEY:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    outputs:
      assets: ${{ steps.release.outputs.assets }}
      url: ${{ steps.release.outputs.url }}
    steps:
      - name: Release
        id: release
        uses: asimov-platform/release-action@v3
        with:
          app_id: ${{ secrets.ASIMOV_APP_ID }}
          app_private_key: ${{ secrets.ASIMOV_APP_PRIVATE_KEY }}
          changelog-path: CHANGES.md
          pattern: "file-*"
